/*
 * Chrona bundled sample timeline
 *
 * Edit this file to review or change the timeline shown to new users and used
 * when a saved Google Sheet cannot be loaded. This file contains no Sheet URL
 * and cannot read another user's browser storage.
 */
window.CHRONA_SAMPLE_DATA = {
  categories: [
    { Group: 'United States', Color: '#2563EB', 'Default Visible': 'TRUE', 'Default Position': 'Above' },
    { Group: 'China', Color: '#DC2626', 'Default Visible': 'TRUE', 'Default Position': 'Below' },
    { Group: 'Ancient Rome', Color: '#7C3AED', 'Default Visible': 'TRUE', 'Default Position': 'Below' },
    { Group: 'Britain', Color: '#D97706', 'Default Visible': 'TRUE', 'Default Position': 'Below' },
    { Group: 'Germany', Color: '#475569', 'Default Visible': 'TRUE', 'Default Position': 'Below' }
  ],
  events: [
    { Year:'1776', Month:'7', Day:'4', 'Display Date':'July 4, 1776', Headline:'U.S. Declaration of Independence', Text:'The thirteen colonies declared independence from Great Britain.', Media:'https://upload.wikimedia.org/wikipedia/commons/1/15/Declaration_independence.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Declaration of Independence', Group:'United States', Type:'Event', Position:'Above', Importance:'Major', Color:'#2563EB', Visible:'TRUE', 'Event ID':'US-1776-DECLARATION' },
    { Year:'1787', Month:'9', Day:'17', 'Display Date':'September 17, 1787', Headline:'U.S. Constitution Signed', Text:'Delegates signed the Constitution in Philadelphia.', Media:'https://upload.wikimedia.org/wikipedia/commons/4/4d/Scene_at_the_Signing_of_the_Constitution_of_the_United_States.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Signing of the U.S. Constitution', Group:'United States', Type:'Event', Position:'Above', Importance:'Major', Color:'#2563EB', Visible:'TRUE', 'Event ID':'US-1787-CONSTITUTION' },
    { Year:'1839', 'End Year':'1842', 'Display Date':'1839–1842', Headline:'First Opium War', Text:'Conflict between Qing China and Britain led to the Treaty of Nanking.', Media:'https://upload.wikimedia.org/wikipedia/commons/0/0e/Destroying_Chinese_war_junks%2C_by_E._Duncan_%281843%29.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Naval battle during the First Opium War', Group:'China', Type:'Event', Position:'Below', Importance:'Major', Color:'#DC2626', Visible:'TRUE', 'Event ID':'CN-1839-OPIUM-WAR-1' },
    { Year:'1861', Month:'4', Day:'12', 'End Year':'1865', 'End Month':'4', 'End Day':'9', 'Display Date':'1861–1865', Headline:'American Civil War', Text:'War between the Union and the Confederacy transformed the United States and ended legal slavery.', Media:'https://upload.wikimedia.org/wikipedia/commons/9/9a/Fall_of_Richmond_Va_on_the_night_of_April_2nd_1865.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Richmond during the Civil War', Group:'United States', Type:'Event', Position:'Above', Importance:'Major', Color:'#2563EB', Visible:'TRUE', 'Event ID':'US-1861-CIVIL-WAR' },
    { Year:'1911', Month:'10', Day:'10', 'End Year':'1912', 'End Month':'2', 'End Day':'12', 'Display Date':'1911–1912', Headline:'Xinhai Revolution', Text:'The revolution ended imperial rule and led to the establishment of the Republic of China.', Media:'https://upload.wikimedia.org/wikipedia/commons/8/8f/Wuchang_Uprising.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Wuchang Uprising', Group:'China', Type:'Event', Position:'Below', Importance:'Major', Color:'#DC2626', Visible:'TRUE', 'Event ID':'CN-1911-XINHAI' },
    { Year:'1929', Month:'10', Day:'24', 'Display Date':'October 1929', Headline:'Wall Street Crash', Text:'The stock-market collapse became a defining event of the Great Depression.', Media:'https://upload.wikimedia.org/wikipedia/commons/4/4c/Crowd_outside_nyse.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Crowd outside the New York Stock Exchange', Group:'United States', Type:'Event', Position:'Above', Importance:'Medium', Color:'#2563EB', Visible:'TRUE', 'Event ID':'US-1929-WALL-STREET' },
    { Year:'1937', Month:'7', Day:'7', 'End Year':'1945', 'End Month':'9', 'End Day':'2', 'Display Date':'1937–1945', Headline:'Second Sino-Japanese War', Text:'Full-scale war between China and Japan became part of the wider Second World War.', Media:'https://upload.wikimedia.org/wikipedia/commons/4/46/Chinese_soldiers_in_house_to_house_fighting_in_Tai%27er_zhuang.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Chinese soldiers during the war', Group:'China', Type:'Event', Position:'Below', Importance:'Major', Color:'#DC2626', Visible:'TRUE', 'Event ID':'CN-1937-SINO-JAPANESE-WAR' },
    { Year:'1949', Month:'10', Day:'1', 'Display Date':'October 1, 1949', Headline:'People’s Republic of China Founded', Text:'Mao Zedong proclaimed the People’s Republic of China in Beijing.', Media:'https://upload.wikimedia.org/wikipedia/commons/5/51/Mao_Zedong_proclaiming_the_establishment_of_the_PRC_in_1949.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Proclamation ceremony in Beijing', Group:'China', Type:'Event', Position:'Below', Importance:'Major', Color:'#DC2626', Visible:'TRUE', 'Event ID':'CN-1949-PRC' },
    { Year:'1969', Month:'7', Day:'20', 'Display Date':'July 20, 1969', Headline:'Apollo 11 Moon Landing', Text:'Neil Armstrong and Buzz Aldrin became the first people to walk on the Moon.', Media:'https://upload.wikimedia.org/wikipedia/commons/9/98/Aldrin_Apollo_11_original.jpg', 'Media Credit':'NASA / Wikimedia Commons', 'Media Caption':'Buzz Aldrin on the Moon', Group:'United States', Type:'Event', Position:'Above', Importance:'Major', Color:'#2563EB', Visible:'TRUE', 'Event ID':'US-1969-APOLLO-11' },
    { Year:'1978', Month:'12', Day:'18', 'Display Date':'December 1978', Headline:'China Begins Reform and Opening', Text:'The Third Plenum marked the beginning of major economic reform under Deng Xiaoping.', Media:'https://upload.wikimedia.org/wikipedia/commons/5/5c/Deng_Xiaoping_1979.jpg', 'Media Credit':'Wikimedia Commons', 'Media Caption':'Deng Xiaoping', Group:'China', Type:'Event', Position:'Below', Importance:'Major', Color:'#DC2626', Visible:'TRUE', 'Event ID':'CN-1978-REFORM' },
    { Year:'-27', 'End Year':'476', 'Display Date':'27 BCE–476 CE', Headline:'Roman Empire (Western)', Text:'Reference period spanning the Roman imperial era in the West.', Group:'Ancient Rome', Type:'Period', Position:'Below', Importance:'Major', Color:'#7C3AED', Visible:'TRUE', 'Event ID':'ROME-0027BCE-0476' },
    { Year:'1707', 'End Year':'1997', 'Display Date':'1707–1997', Headline:'British Empire (broad reference period)', Text:'A simplified reference span for Britain’s imperial period.', Group:'Britain', Type:'Period', Position:'Below', Importance:'Major', Color:'#D97706', Visible:'TRUE', 'Event ID':'GB-1707-1997-EMPIRE' },
    { Year:'1933', 'End Year':'1945', 'Display Date':'1933–1945', Headline:'Nazi Regime', Text:'Period during which Adolf Hitler and the Nazi Party ruled Germany.', Group:'Germany', Type:'Period', Position:'Below', Importance:'Major', Color:'#475569', Visible:'TRUE', 'Event ID':'DE-1933-1945-NAZI' },
    { Year:'1644', 'End Year':'1912', 'Display Date':'1644–1912', Headline:'Qing Dynasty', Text:'China’s final imperial dynasty, used here as a long-duration reference block.', Group:'China', Type:'Period', Position:'Below', Importance:'Major', Color:'#DC2626', Visible:'TRUE', 'Event ID':'CN-1644-1912-QING' }
  ]
};
