/* Generated by tools/finalize-release.command. Do not edit by hand. */
window.CHRONA_VERSION = '2.9.0';
Object.defineProperty(window, 'CHRONA_SAMPLE_DATA', {
  configurable: true,
  get() { return undefined; },
  set(value) {
    if (value && Array.isArray(value.events)) {
      value.events.forEach(event => {
        if (!event['Media Thumbnail'] && event.Media) event['Media Thumbnail'] = event.Media;
      });
    }
    Object.defineProperty(window, 'CHRONA_SAMPLE_DATA', {
      configurable: true,
      writable: true,
      value
    });
  }
});
