#!/usr/bin/env python3
"""Build Chrona's bundled sample-data.js from chrona-sample-timeline.xlsx.

Uses only the Python standard library so it works on a stock Python 3 install.
"""
from __future__ import annotations

import json
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
      "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
      "p": "http://schemas.openxmlformats.org/package/2006/relationships"}


def col_index(ref: str) -> int:
    letters = re.match(r"[A-Z]+", ref)
    if not letters:
        raise ValueError(f"Invalid cell reference: {ref}")
    n = 0
    for ch in letters.group(0):
        n = n * 26 + ord(ch) - 64
    return n - 1


def load_shared_strings(zf: zipfile.ZipFile) -> list[str]:
    try:
        root = ET.fromstring(zf.read("xl/sharedStrings.xml"))
    except KeyError:
        return []
    out = []
    for si in root.findall("m:si", NS):
        out.append("".join(t.text or "" for t in si.iterfind(".//m:t", NS)))
    return out


def sheet_paths(zf: zipfile.ZipFile) -> dict[str, str]:
    wb = ET.fromstring(zf.read("xl/workbook.xml"))
    rels = ET.fromstring(zf.read("xl/_rels/workbook.xml.rels"))
    rel_map = {rel.attrib["Id"]: rel.attrib["Target"] for rel in rels.findall("p:Relationship", NS)}
    result = {}
    for sheet in wb.findall("m:sheets/m:sheet", NS):
        name = sheet.attrib["name"]
        rid = sheet.attrib[f"{{{NS['r']}}}id"]
        target = rel_map[rid].lstrip("/")
        if not target.startswith("xl/"):
            target = "xl/" + target
        result[name] = target
    return result


def cell_value(cell: ET.Element, shared: list[str]):
    t = cell.attrib.get("t")
    if t == "inlineStr":
        return "".join(x.text or "" for x in cell.iterfind(".//m:t", NS))
    v = cell.find("m:v", NS)
    if v is None or v.text is None:
        return None
    raw = v.text
    if t == "s":
        return shared[int(raw)]
    if t == "b":
        return raw == "1"
    if t in {"str", "e"}:
        return raw
    try:
        num = float(raw)
    except ValueError:
        return raw
    return int(num) if num.is_integer() else num


def read_sheet(zf: zipfile.ZipFile, path: str, shared: list[str]) -> list[list[object]]:
    root = ET.fromstring(zf.read(path))
    rows = []
    for row in root.findall("m:sheetData/m:row", NS):
        values: list[object] = []
        for cell in row.findall("m:c", NS):
            idx = col_index(cell.attrib["r"])
            if len(values) <= idx:
                values.extend([None] * (idx + 1 - len(values)))
            values[idx] = cell_value(cell, shared)
        rows.append(values)
    return rows


def rows_to_objects(rows: list[list[object]]) -> list[dict[str, object]]:
    if not rows:
        return []
    headers = [str(x).strip() if x is not None else "" for x in rows[0]]
    objects = []
    for row in rows[1:]:
        obj = {}
        for i, header in enumerate(headers):
            if not header:
                continue
            value = row[i] if i < len(row) else None
            if value is None or value == "":
                continue
            obj[header] = value
        if obj:
            objects.append(obj)
    return objects


def build(workbook: Path, output: Path) -> tuple[int, int, int]:
    with zipfile.ZipFile(workbook) as zf:
        shared = load_shared_strings(zf)
        paths = sheet_paths(zf)
        if "Timeline Data" not in paths or "Config" not in paths:
            raise RuntimeError("Workbook must contain 'Timeline Data' and 'Config' sheets.")
        events = rows_to_objects(read_sheet(zf, paths["Timeline Data"], shared))
        config = rows_to_objects(read_sheet(zf, paths["Config"], shared))
        categories = rows_to_objects(read_sheet(zf, paths["Categories"], shared)) if "Categories" in paths else []

    if not events:
        raise RuntimeError("No timeline events found.")
    missing_ids = [i + 2 for i, event in enumerate(events) if not event.get("Event ID")]
    if missing_ids:
        raise RuntimeError(f"Timeline rows missing Event ID: {missing_ids}")

    payload = {"config": config, "categories": categories, "events": events}
    text = (
        "/*\n"
        " * Chrona bundled public sample timeline.\n"
        " * Generated from chrona-sample-timeline.xlsx by tools/build-sample-data.py.\n"
        " * Do not edit this file by hand.\n"
        " */\n"
        "window.CHRONA_SAMPLE_DATA = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    output.write_text(text, encoding="utf-8")
    media_count = sum(1 for event in events if event.get("Media"))
    groups = len({event.get("Group") for event in events if event.get("Group")})
    return len(events), groups, media_count


def main() -> int:
    repo = Path(__file__).resolve().parent.parent
    workbook = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else repo / "chrona-sample-timeline.xlsx"
    output = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else repo / "sample-data.js"
    if not workbook.exists():
        print(f"ERROR: workbook not found: {workbook}", file=sys.stderr)
        return 1
    try:
        events, groups, media = build(workbook, output)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print("Chrona sample data rebuilt")
    print(f"Events: {events}")
    print(f"Groups: {groups}")
    print(f"Media URLs: {media}")
    print(f"Output: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
