#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

VERSION_FILE="$REPO_DIR/VERSION"
INDEX_FILE="$REPO_DIR/index.html"
VERSION_JS="$REPO_DIR/version.js"
README_FILE="$REPO_DIR/ReadMe.txt"

if [[ ! -f "$VERSION_FILE" || ! -f "$INDEX_FILE" || ! -f "$REPO_DIR/timeline.js" || ! -f "$README_FILE" ]]; then
  echo "ERROR: Run this tool from a complete Chrona project."
  exit 1
fi

current="$(tr -d '[:space:]' < "$VERSION_FILE")"
requested="${1:-}"

if [[ -n "$requested" ]]; then
  next="$requested"
else
  if [[ ! "$current" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    echo "ERROR: VERSION must use MAJOR.MINOR.PATCH format. Found: $current"
    exit 1
  fi
  next="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.$(( BASH_REMATCH[3] + 1 ))"
fi

if [[ ! "$next" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "ERROR: Version must use MAJOR.MINOR.PATCH format, such as 2.1.18."
  exit 1
fi

printf '%s\n' "$next" > "$VERSION_FILE"
cat > "$VERSION_JS" <<VERSIONEOF
/* Generated by tools/finalize-release.command. Do not edit by hand. */
window.CHRONA_VERSION = '$next';
VERSIONEOF

# Synchronize the visible Settings version and every cache-busting asset version.
perl -0pi -e "s/(id=['\"]appVersion['\"][^>]*>\s*)v?[^<]+/\${1}v$next/g; s/\?v=[A-Za-z0-9._-]+/?v=$next/g" "$INDEX_FILE"

# Validate JavaScript syntax when Node is available.
if command -v node >/dev/null 2>&1; then
  while IFS= read -r file; do
    node --check "$file" >/dev/null
  done < <(find . -type f -name '*.js' ! -path './.git/*' ! -path './release/*' | sort)
fi

# Verify the runtime source and all cache references use exactly VERSION.
errors=0
if ! grep -Fq "window.CHRONA_VERSION = '$next';" "$VERSION_JS"; then
  echo "ERROR: version.js does not match VERSION."
  errors=1
fi

if grep -oE '\?v=[0-9]+\.[0-9]+\.[0-9]+' "$INDEX_FILE" | grep -vF "?v=$next" >/dev/null; then
  echo "ERROR: Conflicting cache versions remain in index.html:"
  grep -nE '\?v=[0-9]+\.[0-9]+\.[0-9]+' "$INDEX_FILE" | grep -vF "?v=$next" || true
  errors=1
fi

if ! grep -Fq "id=\"appVersion\">v$next<" "$INDEX_FILE"; then
  echo "ERROR: Settings version does not match VERSION."
  errors=1
fi

if ! grep -Eq "^### ${next//./\.}$" "$README_FILE"; then
  echo "ERROR: ReadMe.txt is missing a version-history entry for $next."
  errors=1
fi


if (( errors != 0 )); then
  exit 1
fi

release_dir="$REPO_DIR/release"
mkdir -p "$release_dir"
zip_path="$release_dir/chrona-v${next}-update.zip"
rm -f "$zip_path"

# Files are stored at ZIP root so users can unzip directly into the existing repo.
zip -qr "$zip_path" . \
  -x '.git/*' \
  -x 'release/*' \
  -x 'dev/*' \
  -x '*.zip' \
  -x '.DS_Store' \
  -x '__MACOSX/*' \
  -x '.chrona-server.pid' \
  -x '.chrona-server.port'

echo
echo "Chrona release finalized"
echo "Version: $next"
echo "Conflicting version references: none"
echo "Package: $zip_path"
